# Generated by Django 2.2.5 on 2019-12-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unnamed Chat', max_length=128, verbose_name='Название чата')),
                ('is_group_chat', models.BooleanField(verbose_name='Групповой')),
                ('topic', models.CharField(max_length=128, verbose_name='Тема чата')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
    ]
