# Generated by Django 2.0 on 2019-10-30 16:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20191030_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 30, 16, 13, 38, 137104, tzinfo=utc)),
        ),
    ]
