# Generated by Django 2.0 on 2019-11-13 09:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_auto_20191106_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chats.Message', verbose_name='Последнее сообщение'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(max_length=16, verbose_name='Тип вложения'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.Chat', verbose_name='Чат вложения'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.Message', verbose_name='Сообщение вложения'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.CharField(max_length=128, verbose_name='Ссылка вложения'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель чата'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_group_chat',
            field=models.BooleanField(verbose_name='Групповой'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(default='Unnamed Chat', max_length=128, verbose_name='Название чата'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='topic',
            field=models.CharField(max_length=128, verbose_name='Тема чата'),
        ),
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 13, 9, 54, 18, 4958, tzinfo=utc), verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.Chat', verbose_name='Чат сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
    ]
