# Generated by Django 2.2.5 on 2019-11-18 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_auto_20191113_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 13, 11, 26, 301160, tzinfo=utc), verbose_name='Дата отправки'),
        ),
    ]
