# Generated by Django 2.2.5 on 2019-11-18 13:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0013_auto_20191118_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 13, 19, 25, 992829, tzinfo=utc), verbose_name='Дата отправки'),
        ),
    ]
