# Generated by Django 2.2.5 on 2019-11-18 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0016_auto_20191118_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 15, 17, 17, 25578, tzinfo=utc), verbose_name='Дата отправки'),
        ),
    ]
