# Generated by Django 2.2.5 on 2019-11-18 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0017_auto_20191118_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 15, 28, 8, 451237, tzinfo=utc), verbose_name='Дата отправки'),
        ),
    ]
