# Generated by Django 2.2.5 on 2019-11-18 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0018_auto_20191118_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 18, 39, 21, 191334, tzinfo=utc), verbose_name='Дата отправки'),
        ),
    ]
