# Generated by Django 2.2.5 on 2019-11-18 18:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0019_auto_20191118_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 18, 41, 44, 302324, tzinfo=utc), verbose_name='Дата отправки'),
        ),
    ]
