# Generated by Django 2.2.5 on 2019-12-02 21:07

import attachment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(max_length=16, verbose_name='Тип вложения')),
                ('file', models.FileField(max_length=10485760, null=True, upload_to=attachment.models.upload_router)),
                ('url', models.CharField(max_length=128, verbose_name='Ссылка вложения')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ('chat',),
            },
        ),
    ]
