# Generated by Django 2.2.5 on 2019-12-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0003_attachment_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='file',
            new_name='content',
        ),
    ]
