# Generated by Django 2.0 on 2019-10-30 12:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.Chat')),
                ('last_read_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.Message')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('nick', models.CharField(max_length=32)),
                ('avatar', models.CharField(max_length=128)),
                ('status', models.CharField(default='Online', max_length=64)),
                ('last_seen', models.DateTimeField(default=datetime.datetime(2019, 10, 30, 12, 1, 43, 449785, tzinfo=utc))),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 10, 30, 12, 1, 43, 449808, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.User'),
        ),
    ]
