# Generated by Django 2.2.5 on 2019-11-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20191118_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=128, null=True, verbose_name='Ссылка на аватар'),
        ),
    ]
